### ISSUE TITLE
Support *https*:://www.wdidc.org (and just wdidc.org - no 'www')

### ISSUE THREAD

**Issue by mattscilipoti** [wdidc/api-students#4]
From assignments, I created a link to "https://students.wdidc.org/#{github_user_id}", but this failed.  The "http" protocol worked.
While we are updating this, can we also support http://wdidc.org (without the 'www')?

**Comment by jshawl** [comment]
1 -  we can support https but this requires purchasing an ssl certificate. usually about $9 per year. but if we want SSL for *.wdidc.org, we'll have to buy a wildcard certificate - about $99 a year

2 - wdidc.org (without www) is hosted on github pages. we can move this to our servers if you want

**Comment by mattscilipoti** [comment]
nvr mind.
